### ISSUE TITLE
[BUG] Payment App not visible after error

### ISSUE THREAD

**Issue by deepakkumardk** [PatilShreyas/EasyUpiPayment-Android#17]
The payment option for different apps got removed after some error during payments in different apps. Now, they are showing less apps (**Apps which have payment failure were not listed in AppBottomSheet**) even after I reinstall the app.

**Comment by PatilShreyas** [comment]
Can you describe full scenario?

**Comment by deepakkumardk** [comment]
Okay this happens in flow:

- First I started payment to whats App -> Alert pop up with message You can't proceed as you haven't setup the payment for this App ( which is fine)
- Then next time when I initialize the EasyUpiPayment WhatsApp wasn't listed there
- This time I proceed with Mobikwik again with some transaction error next time when I initialize Mobikwik wasn't listed there, the same happened with PhonePe.
- And even after I re-installing the these apps aren't showing the list but today (after one day) it's showing those apps

So, the problem is Apps were removed/not shown on the list.

**Comment by PatilShreyas** [comment]
Okay @deepakkumardk. Now I understood the exact problem. This problem isn't associated with this library. Whenever transaction is failing due to some problems, these apps are not listening for payment intents for that, so they aren't found as Intent providers and can't listing those apps there. 

Finally I'm closing this issue as this problem isn't associated with library. Thank you!

**Comment by rajasuman09** [comment]
Sometimes if you try to pay to an account from same account but with different upi ids, this problem comes up.
