### ISSUE TITLE
Fix/Improvements in Documentation

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/EasyUpiPayment-Android#44]
### Proposed change
- Fix or improve the documentation for the library.
- Documentation is available in `/docs` directory.
- Documentation is generated using [Docsify](https://docsify.js.org/).
- This change is encouraged during ***"Hacktoberfest"*** for the participants of this event.

### References
https://docsify.js.org/

**Comment by Priya730** [comment]
Hi! I am new to open source and I propose to fix the existing minor grammatical errors, typos, and other improvements in the documentation:
I can submit the pull request during Hacktoberfest. Please assign this to me so that I can make changes and submit the PR. Also please suggest any further improvements if needed.
Thank you!

**Comment by PatilShreyas** [comment]
Sure! Thanks @Priya730
