### ISSUE TITLE
[BUG/FEATURE REQUEST] This not returning transaction id generated from upi application 

### ISSUE THREAD

**Issue by anurag141** [PatilShreyas/EasyUpiPayment-Android#47]
This not returning transaction id generated from upi application 
so can you please tell me that how can i get transaction id generated form upi application

**Comment by anurag141** [comment]
approvalRefNo:null,

**Comment by PatilShreyas** [comment]
Actually returning transaction ID is the responsibility of UPI apps. But some apps like PhonePe doesn't return transaction ID which is generated by them. You can use `transactionId` for getting transaction ID generated by UPI apps. 

Since this issue isn't associated with this library, I'm closing this issue.

**Comment by anurag141** [comment]
I am not able to get transaction id from other apps also like Google pe ,
and bhim

**Comment by PatilShreyas** [comment]
It's because these apps not returning transaction ID.
