### ISSUE TITLE
Hello sir 

### ISSUE THREAD

**Issue by govindowlok0** [PatilShreyas/EasyUpiPayment-Android#56]
I have install your demo app and try to send amount to user simmiler issue is coming - in gpay , phonepe, paytm 
can you check it in you own demo app please sir 
i used this library last 5 month but last 2 day not working please solve it

in Advance Thank you

**Comment by PatilShreyas** [comment]
As I explained in the previous issue, this is associated with your UPI account as you've exhausted limit of daily UPI transactions. Because only 10 transactions are allowed for a day. If you test it tomorrow, it'll work fine. Because this issue is not related to this library please don't open such issues here.

**Comment by Chhokra** [comment]
@PatilShreyas  this is not true. Because the payment apps are working outside the demo app. But not in the demo app itself. Hence the transaction limit hasn't been reached(neither 10 payments nor 1 lakh INR)

**Comment by govindowlok0** [comment]
please help me i'm doing RND last 2 days not gating success
